[workspace]
members = [
    "sale-report-app/src-tauri"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Sales Report Team"]
license = "MIT"
edition = "2021"
rust-version = "1.77.2"
